---
- name: Test for Grafana and Prometheus Access
  hosts: main
  gather_facts: no
  vars:
    apps: 
      prometheus: 
        port: 9090
        status_code: [302]
      grafana:
        port: 3000
        status_code: [302]
  tasks:
  - name: grafana url check
    ansible.builtin.uri:
      url: "http://{{ inventory_hostname }}:{{ item.value.port }}"
      follow_redirects: none
      status_code: "{{ item.value.status_code }}"
      loop: "{{ lokkup('dict', apps) }}"

  - name: prometheus url check
    ansible.builtin.uri:
      url: http://{{ inventory_hostname }}:9090
      follow_redirects: none
      status_code: [302]
